set nocompatible              " be iMproved, required
filetype off                  " required

if has("win32")
    set rtp+=~/vimfiles/bundle/Vundle.vim/
    let path='~/vimfiles/bundle'
    call vundle#begin(path)
else
    set rtp+=~/.vim/bundle/Vundle.vim/
    call vundle#begin()
endif

set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/syntastic'
Plugin 'altercation/vim-colors-solarized'
Plugin 'scrooloose/nerdtree'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'morhetz/gruvbox'
if has("unix")
  Plugin 'wakatime/vim-wakatime'
  Plugin 'airblade/vim-gitgutter'
endif
call vundle#end()            " required

filetype plugin indent on    " required!

let skip_loading_mswin=1

set shiftwidth=4
set tabstop=4
set softtabstop=4
set autoindent
set expandtab
set smarttab
set smartcase
set nobackup
set ai
" set cul
set showmatch
set vb
set novisualbell
set visualbell t_vb=
set ruler
set laststatus=2
set backspace=indent,eol,start
set showmode
set history=50
let c_comment_strings=1
set hlsearch
set nohlsearch
set scrolloff=3
set showcmd
set number
set incsearch
set ignorecase
set nowb
set noswapfile

" Show EOL type and last modified timestamp, right after the filename
set statusline=%<%F%h%m%r\ [%{&ff}]\ (%{strftime(\"%H:%M\ %d/%m/%Y\",getftime(expand(\"%:p\")))})\ %{fugitive#statusline()}%=%l,%c%V\ %P
" another one -> set statusline=%<%f\%h%m%r%=%-20.(line=%l\ \ col=%c%V\ \ totlin=%L%)\ \ \%h%m%r%=%-40(bytval=0x%B,%n%Y%)\%P

syntax on

if has("gui_running")
  set background=light
  colorscheme solarized
 
  if has("gui_gtk2")
    set guifont=Inconsolata\ 14
  elseif has("gui_macvim")
    set guifont=Menlo\ Regular:h16
  elseif has("gui_win32")
    set guifont=Consolas:h14:cANSI
  endif
else
  if has("unix")
  else
  endif
  set background=dark
  colorscheme gruvbox 
endif

map <F5> :NERDTreeToggle<CR>
nnoremap <C-J> i<CR><Esc>

" Getting out insert mode, alternatives to <Esc> and Ctrl-[
"   Ctrl-L and Alt-L get out of insert mode.
imap <C-L> <ESC>
imap ¬ <ESC>

"  also mashing the keyboard
"  get out of insert mode by mashing the keyboard
" imap j;kl <ESC>
" imap j;lk <ESC>
" imap jk;l <ESC>
" imap jkl; <ESC>
" imap jl;k <ESC>
" imap jlk; <ESC>
" imap kjl; <ESC>
" imap kj;l <ESC>
" imap kl;j <ESC>
" imap klj; <ESC>
" imap k;lj <ESC>
" imap k;jl <ESC>
imap ;lkj <ESC>
" imap ;ljk <ESC>
" imap ;klj <ESC>
" imap ;kjl <ESC>
" imap ;jlk <ESC>
" imap ;jkl <ESC>
" imap l;jk <ESC>
" imap l;kj <ESC>
" imap lkj; <ESC>
" imap ljk; <ESC>
" imap lk;j <ESC>
" imap lj;k <ESC>
" set timeoutlen=500

imap ;; <ESC>

" Ctrl+S to save
nmap <C-S> :w<CR>
imap <C-S> <C-O>:w<CR>

nnoremap <leader>r :w<CR>:!%:p<CR>

" Some remappings to work with the external environment
"   Ctrl+X, Ctrl+C in Visual mode for Cut/Copy external clipboard
"   Ctrl+V in Insert only to Paste external clipboard
"   Alt-Space = system menu
" vnoremap <C-X> "+x
" vnoremap <C-C> "+y
vmap <C-X> "+x
vmap <C-C> "+y
imap <C-V> <C-O>"+gP
" cmap <C-V> <C-R>+
if has("gui")
  noremap <M-Space> :simalt ~<CR>
  inoremap <M-Space> <C-O>:simalt ~<CR>
  cnoremap <M-Space> <C-C>:simalt ~<CR>
endif

map <Leader> <Plug>(easymotion-prefix)

" formats the entire contens as json
" :%!python -m json.tool

