set nocompatible              " be iMproved, required
filetype off                  " required

if has("win32")
    set rtp+=~/vimfiles/bundle/Vundle.vim/
    let path='~/vimfiles/bundle'
    call vundle#begin(path)
else
    set rtp+=~/.vim/bundle/Vundle.vim/
    call vundle#begin()
endif

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/syntastic'
Plugin 'altercation/vim-colors-solarized'
Plugin 'scrooloose/nerdtree'
Plugin 'Lokaltog/vim-easymotion'
call vundle#end()            " required
filetype plugin indent on    " required!

let skip_loading_mswin=1

set shiftwidth=4
set tabstop=4
set softtabstop=4
set autoindent
set expandtab
set smarttab
set smartcase
set nobackup
set ai
" set cul
set showmatch
set vb
set novisualbell
set visualbell t_vb=
set ruler
set laststatus=2
set backspace=indent,eol,start
set showmode
set history=50
let c_comment_strings=1
set hlsearch
set nohlsearch
set scrolloff=3
set showcmd
set number
set incsearch
set ignorecase
set nowb
set noswapfile

" Show EOL type and last modified timestamp, right after the filename
set statusline=%<%F%h%m%r\ [%{&ff}]\ (%{strftime(\"%H:%M\ %d/%m/%Y\",getftime(expand(\"%:p\")))})\ %{fugitive#statusline()}%=%l,%c%V\ %P
" another one -> set statusline=%<%f\%h%m%r%=%-20.(line=%l\ \ col=%c%V\ \ totlin=%L%)\ \ \%h%m%r%=%-40(bytval=0x%B,%n%Y%)\%P

" set lines=25 columns=80

if has("gui_running")
  if has("gui_gtk2")
    set guifont=Inconsolata\ 14
  elseif has("gui_macvim")
    set guifont=Menlo\ Regular:h16
  elseif has("gui_win32")
    set guifont=Consolas:h14:cANSI
  endif
endif

syntax on
let g:solarized_termcolors=256
colorscheme solarized
" set background=dark
" colorscheme desert

map <F5> :NERDTreeToggle<CR>
nnoremap <C-J> i<CR><Esc>

imap <C-L> <ESC>
imap ¬ <ESC>

nmap <c-s> :w<cr>
imap <c-s> <esc>:w<cr>a


" formats the entire contens as json
" :%!python -m json.tool

